//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PricingEntities : DbContext
    {
        public PricingEntities()
            : base("name=PricingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rtblApprovalType> rtblApprovalTypes { get; set; }
        public virtual DbSet<rtblBaseRate> rtblBaseRates { get; set; }
        public virtual DbSet<rtblChannelType> rtblChannelTypes { get; set; }
        public virtual DbSet<rtblConcessionType> rtblConcessionTypes { get; set; }
        public virtual DbSet<rtblConditionProduct> rtblConditionProducts { get; set; }
        public virtual DbSet<rtblConditionType> rtblConditionTypes { get; set; }
        public virtual DbSet<rtblMarketSegment> rtblMarketSegments { get; set; }
        public virtual DbSet<rtblProduct> rtblProducts { get; set; }
        public virtual DbSet<rtblProvince> rtblProvinces { get; set; }
        public virtual DbSet<rtblReviewFeeType> rtblReviewFeeTypes { get; set; }
        public virtual DbSet<rtblRole> rtblRoles { get; set; }
        public virtual DbSet<rtblStatu> rtblStatus { get; set; }
        public virtual DbSet<rtblSubStatu> rtblSubStatus { get; set; }
        public virtual DbSet<rtblTransactionGroup> rtblTransactionGroups { get; set; }
        public virtual DbSet<rtblTransactionType> rtblTransactionTypes { get; set; }
        public virtual DbSet<rtblType> rtblTypes { get; set; }
        public virtual DbSet<tblBolUser> tblBolUsers { get; set; }
        public virtual DbSet<tblBusinesOnlineTransactionType> tblBusinesOnlineTransactionTypes { get; set; }
        public virtual DbSet<tblCentre> tblCentres { get; set; }
        public virtual DbSet<tblCentreBusinessManager> tblCentreBusinessManagers { get; set; }
        public virtual DbSet<tblCentreUser> tblCentreUsers { get; set; }
        public virtual DbSet<tblChannelTypeBaseRate> tblChannelTypeBaseRates { get; set; }
        public virtual DbSet<tblConcessionAccount> tblConcessionAccounts { get; set; }
        public virtual DbSet<tblConcessionApproval> tblConcessionApprovals { get; set; }
        public virtual DbSet<tblConcessionBol> tblConcessionBols { get; set; }
        public virtual DbSet<tblConcessionCash> tblConcessionCashes { get; set; }
        public virtual DbSet<tblConcessionComment> tblConcessionComments { get; set; }
        public virtual DbSet<tblConcessionCondition> tblConcessionConditions { get; set; }
        public virtual DbSet<tblConcessionInvestment> tblConcessionInvestments { get; set; }
        public virtual DbSet<tblConcessionLending> tblConcessionLendings { get; set; }
        public virtual DbSet<tblConcessionMa> tblConcessionMas { get; set; }
        public virtual DbSet<tblConcessionTrade> tblConcessionTrades { get; set; }
        public virtual DbSet<tblConcessionTransactional> tblConcessionTransactionals { get; set; }
        public virtual DbSet<tblConditionTypeProduct> tblConditionTypeProducts { get; set; }
        public virtual DbSet<tblExceptionLog> tblExceptionLogs { get; set; }
        public virtual DbSet<tblLegalEntity> tblLegalEntities { get; set; }
        public virtual DbSet<tblLegalEntityAccount> tblLegalEntityAccounts { get; set; }
        public virtual DbSet<tblRiskGroup> tblRiskGroups { get; set; }
        public virtual DbSet<tblScenarioManagerToolDeal> tblScenarioManagerToolDeals { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblConcession> tblConcessions { get; set; }
    }
}
