//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtblTransactionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rtblTransactionType()
        {
            this.tblConcessionMas = new HashSet<tblConcessionMa>();
            this.tblConcessionTrades = new HashSet<tblConcessionTrade>();
            this.tblConcessionTransactionals = new HashSet<tblConcessionTransactional>();
        }
    
        public int pkTransactionTypeId { get; set; }
        public Nullable<int> fkConcessionTypeId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblConcessionType rtblConcessionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionMa> tblConcessionMas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionTrade> tblConcessionTrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionTransactional> tblConcessionTransactionals { get; set; }
    }
}
