//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinesOnlineTransactionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBusinesOnlineTransactionType()
        {
            this.tblConcessionBols = new HashSet<tblConcessionBol>();
        }
    
        public int pkBusinesOnlineTransactionTypeId { get; set; }
        public int fkTransactionGroupId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblTransactionGroup rtblTransactionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionBol> tblConcessionBols { get; set; }
    }
}
