//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionCondition
    {
        public int pkConcessionConditionId { get; set; }
        public int fkConcessionId { get; set; }
        public int fkConditionTypeId { get; set; }
        public int fkConditionProductId { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Value { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblConditionProduct rtblConditionProduct { get; set; }
        public virtual rtblConditionType rtblConditionType { get; set; }
        public virtual tblConcession tblConcession { get; set; }
    }
}
