//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChannelTypeBaseRate
    {
        public int pkChannelTypeBaseRateId { get; set; }
        public int fkChannelTypeId { get; set; }
        public int fkBaseRateId { get; set; }
    
        public virtual rtblBaseRate rtblBaseRate { get; set; }
        public virtual rtblChannelType rtblChannelType { get; set; }
    }
}
