//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblConcession()
        {
            this.tblConcessionAccounts = new HashSet<tblConcessionAccount>();
            this.tblConcessionApprovals = new HashSet<tblConcessionApproval>();
            this.tblConcessionBols = new HashSet<tblConcessionBol>();
            this.tblConcessionCashes = new HashSet<tblConcessionCash>();
            this.tblConcessionComments = new HashSet<tblConcessionComment>();
            this.tblConcessionConditions = new HashSet<tblConcessionCondition>();
            this.tblConcessionInvestments = new HashSet<tblConcessionInvestment>();
            this.tblConcessionLendings = new HashSet<tblConcessionLending>();
            this.tblConcessionMas = new HashSet<tblConcessionMa>();
            this.tblConcessionTrades = new HashSet<tblConcessionTrade>();
            this.tblConcessionTrades1 = new HashSet<tblConcessionTrade>();
            this.tblConcessionTransactionals = new HashSet<tblConcessionTransactional>();
        }
    
        public int pkConcessionId { get; set; }
        public int fkTypeId { get; set; }
        public string ConcessionRef { get; set; }
        public int fkLegalEntityId { get; set; }
        public int fkConcessionTypeId { get; set; }
        public string SMTDealNumber { get; set; }
        public int fkStatusId { get; set; }
        public Nullable<int> fkSubStatusId { get; set; }
        public System.DateTime ConcessionDate { get; set; }
        public Nullable<System.DateTime> DatesentForApproval { get; set; }
        public string Motivation { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public int fkRequestorId { get; set; }
        public Nullable<int> fkBCMUserId { get; set; }
        public Nullable<System.DateTime> DateActionedByBCM { get; set; }
        public Nullable<int> fkPCMUserId { get; set; }
        public Nullable<System.DateTime> DateActionedByPCM { get; set; }
        public Nullable<int> fkHOUserId { get; set; }
        public Nullable<System.DateTime> DateActionedByHO { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CentreId { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblConcessionType rtblConcessionType { get; set; }
        public virtual rtblStatu rtblStatu { get; set; }
        public virtual rtblSubStatu rtblSubStatu { get; set; }
        public virtual rtblType rtblType { get; set; }
        public virtual tblCentre tblCentre { get; set; }
        public virtual tblLegalEntity tblLegalEntity { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionAccount> tblConcessionAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionApproval> tblConcessionApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionBol> tblConcessionBols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionCash> tblConcessionCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionComment> tblConcessionComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionCondition> tblConcessionConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionInvestment> tblConcessionInvestments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionLending> tblConcessionLendings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionMa> tblConcessionMas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionTrade> tblConcessionTrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionTrade> tblConcessionTrades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcessionTransactional> tblConcessionTransactionals { get; set; }
    }
}
