//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionCash
    {
        public int pkConcessionCashId { get; set; }
        public int fkConcessionId { get; set; }
        public int fkChannelTypeId { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<int> CashVolume { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public Nullable<int> fkBaseRateId { get; set; }
        public Nullable<decimal> AdValorem { get; set; }
    
        public virtual rtblBaseRate rtblBaseRate { get; set; }
        public virtual rtblChannelType rtblChannelType { get; set; }
        public virtual tblConcession tblConcession { get; set; }
    }
}
