//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionBol
    {
        public int pkConcessionBolId { get; set; }
        public Nullable<int> fkConcessionId { get; set; }
        public Nullable<int> fkTransactionGroupId { get; set; }
        public Nullable<int> fkBusinesOnlineTransactionTypeId { get; set; }
        public Nullable<int> BolUseId { get; set; }
        public Nullable<int> TransactionVolume { get; set; }
        public Nullable<decimal> TransactionValue { get; set; }
        public Nullable<decimal> Fee { get; set; }
    
        public virtual rtblTransactionGroup rtblTransactionGroup { get; set; }
        public virtual tblBolUser tblBolUser { get; set; }
        public virtual tblBusinesOnlineTransactionType tblBusinesOnlineTransactionType { get; set; }
        public virtual tblConcession tblConcession { get; set; }
    }
}
