//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCentre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCentre()
        {
            this.tblCentreBusinessManagers = new HashSet<tblCentreBusinessManager>();
            this.tblCentreUsers = new HashSet<tblCentreUser>();
            this.tblConcessions = new HashSet<tblConcession>();
        }
    
        public int pkCentreId { get; set; }
        public int fkProvinceId { get; set; }
        public string CentreName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblProvince rtblProvince { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCentreBusinessManager> tblCentreBusinessManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCentreUser> tblCentreUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcession> tblConcessions { get; set; }
    }
}
