//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionApproval
    {
        public int pkConcessionApprovalId { get; set; }
        public int fkConcessionId { get; set; }
        public Nullable<int> fkOldSubStatusId { get; set; }
        public int fkNewSubStatusId { get; set; }
        public int fkUserId { get; set; }
        public System.DateTime SystemDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblSubStatu rtblSubStatu { get; set; }
        public virtual rtblSubStatu rtblSubStatu1 { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblConcession tblConcession { get; set; }
    }
}
