//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLegalEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLegalEntity()
        {
            this.tblLegalEntityAccounts = new HashSet<tblLegalEntityAccount>();
            this.tblConcessions = new HashSet<tblConcession>();
        }
    
        public int pkLegalEntityId { get; set; }
        public int fkMarketSegmentId { get; set; }
        public int fkRiskGroupId { get; set; }
        public string RiskGroupName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual rtblMarketSegment rtblMarketSegment { get; set; }
        public virtual tblRiskGroup tblRiskGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLegalEntityAccount> tblLegalEntityAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConcession> tblConcessions { get; set; }
    }
}
