//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScenarioManagerToolDeal
    {
        public int pkScenarioManagerToolDealId { get; set; }
        public string DealNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
