//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PricingConcessionsTool.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///
        ///    &lt;table style=&quot;height:350px; border:solid;background-color: transparent;width:700px !important;border-width:thin;border-color:rgb(66, 139, 202); font:Helvetica Neue,Helvetica,Arial,sans-serif&quot;&gt;
        ///        &lt;thead style=&quot;width:100%; background-color:rgb(66, 139, 202);height:30px;&quot;&gt;
        ///
        ///            &lt;tr&gt;
        ///                &lt;th colspan=&quot;2&quot;&gt;
        ///                    &lt;!--Complaint re-assigned--&gt;
        ///
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///
        ///    &lt;table style=&quot;height:350px; border:solid;background-color: transparent;width:700px !important;border-width:thin;border-color:rgb(66, 139, 202); font:Helvetica Neue,Helvetica,Arial,sans-serif&quot;&gt;
        ///        &lt;thead style=&quot;width:100%; background-color:rgb(66, 139, 202);height:30px;&quot;&gt;
        ///
        ///            &lt;tr&gt;
        ///                &lt;th colspan=&quot;2&quot;&gt;
        ///                    &lt;!--Complaint re-assigned--&gt;
        ///
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApprovedWithChanges {
            get {
                return ResourceManager.GetString("ApprovedWithChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///
        ///    &lt;table style=&quot;height:350px; border:solid;background-color: transparent;width:700px !important;border-width:thin;border-color:rgb(66, 139, 202); font:Helvetica Neue,Helvetica,Arial,sans-serif&quot;&gt;
        ///        &lt;thead style=&quot;width:100%; background-color:rgb(66, 139, 202);height:30px;&quot;&gt;
        ///
        ///            &lt;tr&gt;
        ///                &lt;th colspan=&quot;2&quot;&gt;
        ///                    &lt;!--Complaint re-assigned--&gt;
        ///
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///
        ///    &lt;table style=&quot;height:350px; border:solid;background-color: transparent;width:700px !important;border-width:thin;border-color:rgb(66, 139, 202); font:Helvetica Neue,Helvetica,Arial,sans-serif&quot;&gt;
        ///        &lt;thead style=&quot;width:100%; background-color:rgb(66, 139, 202);height:30px;&quot;&gt;
        ///
        ///            &lt;tr&gt;
        ///                &lt;th colspan=&quot;2&quot;&gt;
        ///                    &lt;!--Complaint re-assigned--&gt;
        ///
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewConcession {
            get {
                return ResourceManager.GetString("NewConcession", resourceCulture);
            }
        }
    }
}
