CREATE TABLE [dbo].[SMTRawData] (
    [DealID]                         VARCHAR (50)    NOT NULL,
    [DealSubmitDate]                 DATETIME2 (3)   NULL,
    [Status]                         VARCHAR (20)    NULL,
    [Segment]                        VARCHAR (50)    NULL,
    [USER NAME]                      VARCHAR (101)   NULL,
    [Risk_Group_Cd]                  INT             NULL,
    [Risk_Group_Type]                VARCHAR (20)    NULL,
    [Risk_Group_Name]                VARCHAR (50)    NULL,
    [RGHeadlineEarnings]             DECIMAL (18, 2) NOT NULL,
    [After Deal HE]                  DECIMAL (18, 2) NULL,
    [RGROE]                          DECIMAL (10, 5) NOT NULL,
    [RGCapital]                      DECIMAL (18, 2) NOT NULL,
    [RGOI]                           DECIMAL (18, 2) NOT NULL,
    [DealROE]                        DECIMAL (10, 5) NULL,
    [DealCapital]                    DECIMAL (18, 2) NULL,
    [DealOI]                         DECIMAL (29, 7) NULL,
    [BASE QUADRANT]                  VARCHAR (16)    NOT NULL,
    [DEAL QUADRANT]                  VARCHAR (16)    NULL,
    [Mandate Quadrant Pass?]         VARCHAR (3)     NOT NULL,
    [Mandate Lending Pass?]          VARCHAR (3)     NOT NULL,
    [Mandate Branch R100m Exceeded?] VARCHAR (3)     NOT NULL,
    [Mandate Branch ADVL Pass?]      VARCHAR (3)     NOT NULL,
    [Mandate Centre R100m Exceeded?] VARCHAR (3)     NOT NULL,
    [Mandate Centre ADVL Pass?]      VARCHAR (3)     NOT NULL,
    [Mandate Auto R100m Exceeded?]   VARCHAR (3)     NOT NULL,
    [Mandate Auto ADVL Pass?]        VARCHAR (3)     NOT NULL,
    [Mandate BOL Pass?]              VARCHAR (3)     NOT NULL,
    [Lending Profit]                 DECIMAL (18, 2) NULL,
    [Lending ROE]                    DECIMAL (18, 2) NULL,
    [Lending Equity]                 DECIMAL (18, 2) NULL,
    [Lending OI]                     DECIMAL (18, 2) NULL,
    [BOL Interchange]                DECIMAL (18, 2) NULL,
    [BOL Profit]                     DECIMAL (18, 2) NULL,
    [BOL Revenue]                    DECIMAL (18, 2) NULL,
    [BOL Capital]                    DECIMAL (18, 2) NULL,
    [CASH Branch Volume]             INT             NULL,
    [CASH Centre Volume]             INT             NULL,
    [CASH Auto Volume]               INT             NULL,
    [CASH Branch Value]              DECIMAL (18, 2) NULL,
    [CASH Centre Value]              DECIMAL (18, 2) NULL,
    [CASH Auto Value]                DECIMAL (18, 2) NULL,
    [CASH Branch Base]               INT             NULL,
    [CASH Centre Base]               INT             NULL,
    [CASH Auto Base]                 INT             NULL,
    [CASH Branch Ad Valorem]         DECIMAL (18, 2) NULL,
    [CASH Centre Ad Valorem]         DECIMAL (18, 2) NULL,
    [CASH Auto Ad Valorem]           DECIMAL (18, 2) NULL,
    [CASH Branch Profit]             DECIMAL (18, 2) NULL,
    [CASH Centre Profit]             DECIMAL (18, 2) NULL,
    [CASH Auto Profit]               DECIMAL (18, 2) NULL,
    [CASH Branch Capital]            DECIMAL (18, 2) NULL,
    [CASH Centre Capital]            DECIMAL (18, 2) NULL,
    [CASH Auto Capital]              DECIMAL (18, 2) NULL,
    [CASH Branch OI]                 DECIMAL (18, 2) NULL,
    [CASH Centre OI]                 DECIMAL (18, 2) NULL,
    [CASH Auto OI]                   DECIMAL (18, 2) NULL
);

