CREATE TABLE [dbo].[rtblTableNumber](
	[pkTableNumberId] [int] IDENTITY(1,1) NOT NULL,
	[TariffTable] [int] NOT NULL,
	[AdValorem] [decimal](18, 2) NULL,
	[BaseRate] [decimal](18, 3) NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_rtblTableNumber] PRIMARY KEY CLUSTERED 
(
	[pkTableNumberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[rtblTableNumber] ADD  CONSTRAINT [DF_rtblTableNumber_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

CREATE TABLE [Audit].[rtblTableNumber] (
	[pkAuditTableNumberId] int IDENTITY(1,1) NOT NULL,
	[pkTableNumberId] int NOT NULL,
	[fkAuditTypeId] int NOT NULL,
	[Entity] xml NOT NULL,
	[Username] varchar(50) NOT NULL,
	[DateStamp] datetime NOT NULL,
CONSTRAINT [PK_Audit_rtblTableNumber] PRIMARY KEY CLUSTERED 
(
	[pkAuditTableNumberId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [Audit].[rtblTableNumber] ADD  CONSTRAINT [DF_Audit_rtblTableNumber_DateStamp]  DEFAULT (getdate()) FOR [DateStamp]
GO

ALTER TABLE [Audit].[rtblTableNumber] WITH CHECK ADD  CONSTRAINT [FK_Audit_rtblTableNumber_AuditType] FOREIGN KEY([fkAuditTypeId])
REFERENCES [Audit].[AuditType] ([Id])
GO

ALTER TABLE [Audit].[rtblTableNumber] CHECK CONSTRAINT [FK_Audit_rtblTableNumber_AuditType]
GO

INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (30, 0, NULL)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (936, 0, 0.222)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (278, 0, 0.2)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (137, 0, 0.29)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (933, 6, 0.15)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (896, 0, 0.15)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (798, 0, 0.161)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (862, 0, 0.161)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (869, 0, 0.161)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (854, 0, 0.161)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (914, 0, 0.172)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (918, 0, 0.16)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (863, 0, 0.183)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (738, 0, 0.183)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (861, 0, 0.194)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (732, 0, 0.194)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (59, 0, 0.204)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (763, 0, 0.215)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (796, 0, 0.216)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (860, 0, 0.216)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (627, 0, 0.226)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (643, 0, 0.227)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (915, 0, 0.23)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (897, 0, 0.239)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (648, 0, 0.241)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (765, 0, 0.25)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (906, 0, 0.262)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (902, 0, 0.262)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (693, 0, 0.269)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (775, 0, 0.28)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (865, 0, 0.284)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (791, 0, 0.294)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (774, 0, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (907, 0, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (911, 0, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (69, 0, 0.312)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (726, 0, 0.312)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (735, 0, 0.323)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (642, 0, 0.333)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (858, 0, 0.35)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (85, 0, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (773, 0, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (857, 0, 0.366)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (768, 0, 0.37)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (752, 0, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (764, 0, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (901, 0, 0.383)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (181, 0, 0.398)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (891, 0, 0.398)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (727, 0, 0.409)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (919, 0, 0.409)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (654, 0, 0.419)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (772, 0, 0.42)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (651, 0, 0.43)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (853, 0, 0.4)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (759, 0, 0.431)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (93, 0, 0.443)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (682, 0, 0.449)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (730, 0, 0.454)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (890, 0, 0.454)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (629, 0, 0.465)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (889, 0, 0.465)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (48, 0, 0.477)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (605, 0, 0.505)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (781, 0, 0.51)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (920, 0, 0.516)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (250, 0, 0.538)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (109, 0, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (433, 0, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (882, 0, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (787, 0, 0.625)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (636, 0, 0.647)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (870, 0, 0.65)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (875, 0, 0.7)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (640, 0, 0.71)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (769, 0, 0.71)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (876, 0, 0.71)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (905, 0, 0.77)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (899, 0, 0.785)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (874, 0, 0.81)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (898, 0, 0.828)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (797, 0, 0.862)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (91, 0, 0.874)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (767, 0, 0.885)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (710, 0, 0.9)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (766, 0, 0.907)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (910, 0, 0.93)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (921, 0, 0.968)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (793, 0, 0.98)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (913, 0, 1.021)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (788, 0, 1.078)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (877, 0, 1.09)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (879, 0, 1.57)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (908, 0, 1.66)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (904, 0, 1.699)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (789, 2.5, 0.647)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (350, 2.5, 1.408)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (868, 3.2, 0)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (916, 4, 0.333)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (747, 6, 0.194)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (925, 6, 0.215)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (909, 6, 0.226)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (924, 6, 0.237)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (440, 6, 0.25)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (439, 6, 0.261)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (799, 6, 0.273)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (690, 6, 0.284)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (635, 6, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (546, 6, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (866, 6, 0.312)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (708, 6, 0.323)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (33, 6, 0.333)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (32, 6, 0.344)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (249, 6, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (31, 6, 0.366)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (883, 6, 0.366)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (885, 6, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (136, 6, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (51, 6, 0.409)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (65, 6, 0.431)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (668, 6, 0.454)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (107, 6, 0.477)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (37, 6, 0.505)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (723, 6, 0.516)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (670, 6, 0.538)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (895, 6, 0.548)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (45, 6, 0.548)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (685, 6, 0.559)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (637, 6, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (700, 6, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (663, 6, 0.613)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (680, 6, 0.635)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (705, 6, 0.647)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (659, 6, 0.658)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (660, 6, 0.67)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (709, 6, 0.68)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (701, 6, 0.68)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (698, 6, 0.692)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (702, 6, 0.71)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (683, 6, 0.731)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (887, 6, 0.742)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (671, 6, 0.742)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (699, 6, 0.763)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (893, 6, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (661, 6, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (686, 6, 0.829)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (707, 6, 0.851)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (652, 6, 0.885)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (689, 6, 0.925)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (687, 6, 0.946)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (695, 6, 0.978)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (711, 6, 1)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (692, 6, 1.021)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (658, 6, 1.044)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (666, 6, 1.066)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (688, 6, 1.101)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (664, 6, 1.129)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (674, 6, 1.183)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (667, 6, 1.236)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (694, 6, 1.248)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (152, 6, 1.305)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (684, 6, 1.344)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (343, 6, 1.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (703, 6, 1.408)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (655, 6, 1.419)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (679, 6, 1.497)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (650, 6, 1.57)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (696, 6, 1.623)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (656, 6, 1.69)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (697, 6, 1.806)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (665, 6, 1.828)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (681, 6, 1.894)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (347, 6, 1.929)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (746, 7, 0.194)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (436, 7, 0.261)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (691, 7, 0.284)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (437, 7, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (545, 7, 0.301)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (66, 7, 0.333)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (645, 7, 0.344)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (274, 7, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (42, 7, 0.366)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (282, 7, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (762, 7, 0.409)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (903, 0, 0.55)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (64, 7, 0.431)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (741, 7, 0.452)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (776, 7, 0.454)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (673, 7, 0.477)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (744, 7, 0.505)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (120, 7, 0.516)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (177, 7, 0.538)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (888, 7, 0.538)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (657, 7, 0.548)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (101, 7, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (121, 7, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (46, 7, 0.613)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (35, 7, 0.635)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (104, 7, 0.647)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (604, 7, 0.658)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (105, 7, 0.67)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (884, 7, 0.67)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (193, 7, 0.68)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (706, 7, 0.68)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (56, 7, 0.692)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (737, 7, 0.71)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (263, 7, 0.731)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (50, 7, 0.742)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (96, 7, 0.763)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (43, 7, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (881, 7, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (258, 7, 0.829)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (52, 7, 0.851)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (438, 7, 0.885)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (124, 7, 0.925)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (892, 7, 0.925)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (894, 7, 0.925)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (190, 7, 0.946)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (197, 7, 0.978)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (234, 7, 1)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (601, 7, 1.021)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (170, 7, 1.044)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (53, 7, 1.066)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (653, 7, 1.101)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (99, 7, 1.129)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (317, 7, 1.183)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (95, 7, 1.236)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (886, 7, 1.236)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (116, 7, 1.248)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (44, 7, 1.305)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (128, 7, 1.344)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (273, 7, 1.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (117, 7, 1.408)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (129, 7, 1.419)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (132, 7, 1.497)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (131, 7, 1.57)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (112, 7, 1.623)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (133, 7, 1.69)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (419, 7, 1.806)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (138, 7, 1.828)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (140, 7, 1.894)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (141, 7, 1.929)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (900, 0, 0.074)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (855, 0, 0.118)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (751, 0, 0.136)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (676, 0, 0.137)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (614, 0, 0.139)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (880, 0, 0.144)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (912, 0, 0.159)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (778, 0, 0.176)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (782, 0, 0.211)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (760, 0, 0.212)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (779, 0, 0.224)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (780, 0, 0.23)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (748, 0, 0.236)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (603, 0, 0.237)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (758, 0, 0.24)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (731, 0, 0.249)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (644, 0, 0.249)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (864, 0, 0.256)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (749, 0, 0.262)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (628, 0, 0.266)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (725, 0, 0.294)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (777, 0, 0.294)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (728, 0, 0.299)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (761, 0, 0.18)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (646, 0, 0.31)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (750, 0, 0.312)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (754, 0, 0.312)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (721, 0, 0.325)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (757, 0, 0.329)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (631, 0, 0.333)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (739, 0, 0.336)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (704, 0, 0.345)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (724, 0, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (734, 0, 0.355)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (733, 0, 0.366)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (647, 0, 0.388)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (756, 0, 0.388)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (742, 0, 0.421)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (753, 0, 0.436)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (856, 0, 0.458)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (662, 0, 0.459)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (755, 0, 0.471)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (675, 0, 0.538)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (736, 0, 0.577)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (771, 0, 0.933)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (740, 0, 0.998)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (729, 0, 1.476)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (859, 1.5, 0)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (119, 4.18, 0.433)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (619, 4.18, 0.5)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (36, 6, 0.581)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (36, 6, 0.387)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (39, 7, 0.634)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (39, 7, 0.495)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (40, 7, 0.914)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (40, 7, 0.742)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (41, 7, 1.032)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (41, 7, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (47, 6, 0.634)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (47, 6, 0.495)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (49, 7, 0.914)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (49, 7, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (55, 6, 0.495)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (55, 6, 0.376)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (63, 7, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (63, 7, 0.495)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (67, 6, 0.914)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (67, 6, 0.742)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (94, 6, 1.032)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (94, 6, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (125, 6, 1.15)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (125, 6, 0.98)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (281, 6, 0.914)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (281, 6, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (283, 6, 0.796)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (283, 6, 0.495)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (669, 6, 1.011)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (669, 6, 0.935)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (785, 0, 1.161)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (785, 0, 0.699)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (785, 0, 0.559)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (786, 0, 1.774)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (786, 0, 1.089)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (786, 0, 0.753)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (139, 7, 1.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (139, 7, 1.6)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (139, 7, 1.27)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (199, 7, 1.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (199, 7, 1.6)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (199, 7, 1.27)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (260, 7, 1.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (260, 7, 1.6)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (260, 7, 1.27)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (284, 6, 1.8)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (284, 6, 1.32)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (284, 6, 0.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (302, 7, 1.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (302, 7, 1.6)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (302, 7, 1.27)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (639, 7, 1.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (639, 7, 1.6)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (639, 7, 1.27)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (716, 6, 1.8)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (716, 6, 1.32)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (716, 6, 0.95)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (300, 4, 0.9)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (638, 4, 0.9)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (715, 6, 1)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (213, 8, 1.8)
INSERT INTO [dbo].[rtblTableNumber] ([TariffTable], [AdValorem], [BaseRate]) VALUES (130, 7, 1.32)

GO

--DROP STATISTICS [tblConcessionCash].[TableNumber]

--GO

ALTER TABLE [dbo].[tblConcessionCash]
DROP COLUMN [TableNumber]

GO

ALTER TABLE [dbo].[tblConcessionCash]
ADD [fkTableNumberId] int NULL

GO

UPDATE [dbo].[tblConcessionCash]
SET [fkTableNumberId] = (SELECT TOP 1 [pkTableNumberId] FROM [dbo].[rtblTableNumber])

GO

ALTER TABLE [dbo].[tblConcessionCash]
ALTER COLUMN [fkTableNumberId] int NOT NULL

GO


ALTER TABLE [dbo].[tblConcessionCash]  WITH CHECK ADD  CONSTRAINT [FK_tblConcessionCash_rtblTableNumber] FOREIGN KEY([fkTableNumberId])
REFERENCES [dbo].[rtblTableNumber] ([pkTableNumberId])
GO

ALTER TABLE [dbo].[tblConcessionCash] CHECK CONSTRAINT [FK_tblConcessionCash_rtblTableNumber]
GO


ALTER TABLE [dbo].[tblConcessionCash]
ALTER COLUMN [BaseRate] decimal(18,3) null

GO

