//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingConcessionsTool.Services.AD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldType", Namespace="http://tempuri.org/")]
    public enum FieldType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surname = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANumber = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ANumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullyQualifiedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ANumber {
            get {
                return this.ANumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ANumberField, value) != true)) {
                    this.ANumberField = value;
                    this.RaisePropertyChanged("ANumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FullyQualifiedName {
            get {
                return this.FullyQualifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullyQualifiedNameField, value) != true)) {
                    this.FullyQualifiedNameField = value;
                    this.RaisePropertyChanged("FullyQualifiedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AD.ActiveDirectorySoap")]
    public interface ActiveDirectorySoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateEmail", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.ValidateEmailResponse ValidateEmail(PricingConcessionsTool.Services.AD.ValidateEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.ValidateEmailResponse> ValidateEmailAsync(PricingConcessionsTool.Services.AD.ValidateEmailRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserString", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.GetUserStringResponse GetUserString(PricingConcessionsTool.Services.AD.GetUserStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserString", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserStringResponse> GetUserStringAsync(PricingConcessionsTool.Services.AD.GetUserStringRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersDetialsDelimited", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse GetUsersDetialsDelimited(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersDetialsDelimited", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse> GetUsersDetialsDelimitedAsync(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserOnDomain", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.GetUserOnDomainResponse GetUserOnDomain(PricingConcessionsTool.Services.AD.GetUserOnDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserOnDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserOnDomainResponse> GetUserOnDomainAsync(PricingConcessionsTool.Services.AD.GetUserOnDomainRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.GetUserResponse GetUser(PricingConcessionsTool.Services.AD.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserResponse> GetUserAsync(PricingConcessionsTool.Services.AD.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        PricingConcessionsTool.Services.AD.GetUsersResponse GetUsers(PricingConcessionsTool.Services.AD.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersResponse> GetUsersAsync(PricingConcessionsTool.Services.AD.GetUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateEmail", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.ValidateEmailRequestBody Body;
        
        public ValidateEmailRequest() {
        }
        
        public ValidateEmailRequest(PricingConcessionsTool.Services.AD.ValidateEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ValidateEmailRequestBody() {
        }
        
        public ValidateEmailRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.ValidateEmailResponseBody Body;
        
        public ValidateEmailResponse() {
        }
        
        public ValidateEmailResponse(PricingConcessionsTool.Services.AD.ValidateEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateEmailResult;
        
        public ValidateEmailResponseBody() {
        }
        
        public ValidateEmailResponseBody(bool ValidateEmailResult) {
            this.ValidateEmailResult = ValidateEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserString", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserStringRequestBody Body;
        
        public GetUserStringRequest() {
        }
        
        public GetUserStringRequest(PricingConcessionsTool.Services.AD.GetUserStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PricingConcessionsTool.Services.AD.FieldType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public GetUserStringRequestBody() {
        }
        
        public GetUserStringRequestBody(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            this.type = type;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserStringResponseBody Body;
        
        public GetUserStringResponse() {
        }
        
        public GetUserStringResponse(PricingConcessionsTool.Services.AD.GetUserStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserStringResult;
        
        public GetUserStringResponseBody() {
        }
        
        public GetUserStringResponseBody(string GetUserStringResult) {
            this.GetUserStringResult = GetUserStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersDetialsDelimitedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersDetialsDelimited", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequestBody Body;
        
        public GetUsersDetialsDelimitedRequest() {
        }
        
        public GetUsersDetialsDelimitedRequest(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersDetialsDelimitedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PricingConcessionsTool.Services.AD.FieldType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int limit;
        
        public GetUsersDetialsDelimitedRequestBody() {
        }
        
        public GetUsersDetialsDelimitedRequestBody(PricingConcessionsTool.Services.AD.FieldType type, string value, int limit) {
            this.type = type;
            this.value = value;
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersDetialsDelimitedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersDetialsDelimitedResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponseBody Body;
        
        public GetUsersDetialsDelimitedResponse() {
        }
        
        public GetUsersDetialsDelimitedResponse(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersDetialsDelimitedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsersDetialsDelimitedResult;
        
        public GetUsersDetialsDelimitedResponseBody() {
        }
        
        public GetUsersDetialsDelimitedResponseBody(string GetUsersDetialsDelimitedResult) {
            this.GetUsersDetialsDelimitedResult = GetUsersDetialsDelimitedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserOnDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserOnDomain", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserOnDomainRequestBody Body;
        
        public GetUserOnDomainRequest() {
        }
        
        public GetUserOnDomainRequest(PricingConcessionsTool.Services.AD.GetUserOnDomainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserOnDomainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PricingConcessionsTool.Services.AD.FieldType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain;
        
        public GetUserOnDomainRequestBody() {
        }
        
        public GetUserOnDomainRequestBody(PricingConcessionsTool.Services.AD.FieldType type, string value, string domain) {
            this.type = type;
            this.value = value;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserOnDomainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserOnDomainResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserOnDomainResponseBody Body;
        
        public GetUserOnDomainResponse() {
        }
        
        public GetUserOnDomainResponse(PricingConcessionsTool.Services.AD.GetUserOnDomainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserOnDomainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PricingConcessionsTool.Services.AD.User GetUserOnDomainResult;
        
        public GetUserOnDomainResponseBody() {
        }
        
        public GetUserOnDomainResponseBody(PricingConcessionsTool.Services.AD.User GetUserOnDomainResult) {
            this.GetUserOnDomainResult = GetUserOnDomainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(PricingConcessionsTool.Services.AD.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PricingConcessionsTool.Services.AD.FieldType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            this.type = type;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(PricingConcessionsTool.Services.AD.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PricingConcessionsTool.Services.AD.User GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(PricingConcessionsTool.Services.AD.User GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(PricingConcessionsTool.Services.AD.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PricingConcessionsTool.Services.AD.FieldType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public GetUsersRequestBody() {
        }
        
        public GetUsersRequestBody(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            this.type = type;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public PricingConcessionsTool.Services.AD.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(PricingConcessionsTool.Services.AD.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PricingConcessionsTool.Services.AD.User[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(PricingConcessionsTool.Services.AD.User[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActiveDirectorySoapChannel : PricingConcessionsTool.Services.AD.ActiveDirectorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActiveDirectorySoapClient : System.ServiceModel.ClientBase<PricingConcessionsTool.Services.AD.ActiveDirectorySoap>, PricingConcessionsTool.Services.AD.ActiveDirectorySoap {
        
        public ActiveDirectorySoapClient() {
        }
        
        public ActiveDirectorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActiveDirectorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.ValidateEmailResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.ValidateEmail(PricingConcessionsTool.Services.AD.ValidateEmailRequest request) {
            return base.Channel.ValidateEmail(request);
        }
        
        public bool ValidateEmail(string email) {
            PricingConcessionsTool.Services.AD.ValidateEmailRequest inValue = new PricingConcessionsTool.Services.AD.ValidateEmailRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.ValidateEmailRequestBody();
            inValue.Body.email = email;
            PricingConcessionsTool.Services.AD.ValidateEmailResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).ValidateEmail(inValue);
            return retVal.Body.ValidateEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.ValidateEmailResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.ValidateEmailAsync(PricingConcessionsTool.Services.AD.ValidateEmailRequest request) {
            return base.Channel.ValidateEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.ValidateEmailResponse> ValidateEmailAsync(string email) {
            PricingConcessionsTool.Services.AD.ValidateEmailRequest inValue = new PricingConcessionsTool.Services.AD.ValidateEmailRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.ValidateEmailRequestBody();
            inValue.Body.email = email;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).ValidateEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.GetUserStringResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUserString(PricingConcessionsTool.Services.AD.GetUserStringRequest request) {
            return base.Channel.GetUserString(request);
        }
        
        public string GetUserString(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUserStringRequest inValue = new PricingConcessionsTool.Services.AD.GetUserStringRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserStringRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            PricingConcessionsTool.Services.AD.GetUserStringResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUserString(inValue);
            return retVal.Body.GetUserStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserStringResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUserStringAsync(PricingConcessionsTool.Services.AD.GetUserStringRequest request) {
            return base.Channel.GetUserStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserStringResponse> GetUserStringAsync(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUserStringRequest inValue = new PricingConcessionsTool.Services.AD.GetUserStringRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserStringRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUserStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUsersDetialsDelimited(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest request) {
            return base.Channel.GetUsersDetialsDelimited(request);
        }
        
        public string GetUsersDetialsDelimited(PricingConcessionsTool.Services.AD.FieldType type, string value, int limit) {
            PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest inValue = new PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            inValue.Body.limit = limit;
            PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUsersDetialsDelimited(inValue);
            return retVal.Body.GetUsersDetialsDelimitedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUsersDetialsDelimitedAsync(PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest request) {
            return base.Channel.GetUsersDetialsDelimitedAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedResponse> GetUsersDetialsDelimitedAsync(PricingConcessionsTool.Services.AD.FieldType type, string value, int limit) {
            PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest inValue = new PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUsersDetialsDelimitedRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            inValue.Body.limit = limit;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUsersDetialsDelimitedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.GetUserOnDomainResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUserOnDomain(PricingConcessionsTool.Services.AD.GetUserOnDomainRequest request) {
            return base.Channel.GetUserOnDomain(request);
        }
        
        public PricingConcessionsTool.Services.AD.User GetUserOnDomain(PricingConcessionsTool.Services.AD.FieldType type, string value, string domain) {
            PricingConcessionsTool.Services.AD.GetUserOnDomainRequest inValue = new PricingConcessionsTool.Services.AD.GetUserOnDomainRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserOnDomainRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            inValue.Body.domain = domain;
            PricingConcessionsTool.Services.AD.GetUserOnDomainResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUserOnDomain(inValue);
            return retVal.Body.GetUserOnDomainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserOnDomainResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUserOnDomainAsync(PricingConcessionsTool.Services.AD.GetUserOnDomainRequest request) {
            return base.Channel.GetUserOnDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserOnDomainResponse> GetUserOnDomainAsync(PricingConcessionsTool.Services.AD.FieldType type, string value, string domain) {
            PricingConcessionsTool.Services.AD.GetUserOnDomainRequest inValue = new PricingConcessionsTool.Services.AD.GetUserOnDomainRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserOnDomainRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            inValue.Body.domain = domain;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUserOnDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.GetUserResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUser(PricingConcessionsTool.Services.AD.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public PricingConcessionsTool.Services.AD.User GetUser(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUserRequest inValue = new PricingConcessionsTool.Services.AD.GetUserRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            PricingConcessionsTool.Services.AD.GetUserResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUserAsync(PricingConcessionsTool.Services.AD.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUserResponse> GetUserAsync(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUserRequest inValue = new PricingConcessionsTool.Services.AD.GetUserRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUserRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PricingConcessionsTool.Services.AD.GetUsersResponse PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUsers(PricingConcessionsTool.Services.AD.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public PricingConcessionsTool.Services.AD.User[] GetUsers(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUsersRequest inValue = new PricingConcessionsTool.Services.AD.GetUsersRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUsersRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            PricingConcessionsTool.Services.AD.GetUsersResponse retVal = ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersResponse> PricingConcessionsTool.Services.AD.ActiveDirectorySoap.GetUsersAsync(PricingConcessionsTool.Services.AD.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PricingConcessionsTool.Services.AD.GetUsersResponse> GetUsersAsync(PricingConcessionsTool.Services.AD.FieldType type, string value) {
            PricingConcessionsTool.Services.AD.GetUsersRequest inValue = new PricingConcessionsTool.Services.AD.GetUsersRequest();
            inValue.Body = new PricingConcessionsTool.Services.AD.GetUsersRequestBody();
            inValue.Body.type = type;
            inValue.Body.value = value;
            return ((PricingConcessionsTool.Services.AD.ActiveDirectorySoap)(this)).GetUsersAsync(inValue);
        }
    }
}
